apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-password
  namespace: default
spec:
  encryptedData:
    password: AgAmrLCQswBxFkqiCdy5/alA+0FfClo1GCz5iLffH1ba267lfOYc60bOSYALX55+S/4RBohu3s3snKagx5mkhktxzzeX2McfqXre/Yk4u5wHs7YD8Q5ilPJlQBw+mwS5QvKw+Mnq54iPM7lW1GcNjhfm4Ylm9vS+tYc5q6gENYPnVzFBt5ZvtmxIOSitMarL7wTu2tw+ASDW0m4p8GFMc19z99b1u6xqiuNGb/N5V+Q4H/3+N3QajzAkqO+5uih2Qu4tKcelHFnaufcfyjab4FIwoVf2cV2Wfu6aoOKPAqA57m8N84ZTUvVCTBJxgd5HVWvovclnXpiwB6k/Iq+aOLQCRRIyuncilvRZZbGT9EXP2rK2NTX8i+IhOqq6qhu36O14U/sE8Xd5/iDTbZjvh2Il0S3SuMcAsMP5cqx7rc12cPFc28/ksiAmLoeqzu1VoIJpp8zfIOQqG82/6MoAqBVgTy0xXxNl79XPyz7dv2lsCrOrZp5f5uq38Y3EzJU9BMSRolLM5Lf4NeBSxr2SGYhNwcq08x0ahDJ+6lC1jULXuZhVq58RH7voiC6PhI5YSl86a6+Qx0w7U+UHeihJw4mFwS+lfC0RY1j1tQTLcW4L9PkuOC6u7A6vOlLBgoRzO5aj0Kj74iAEOQ/ZtYNeb6WQmVUSxUeM43q8ynIg04muQwZAIV33No+jiFGmUPGSGwVCosuj426MzTO+tqE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-password
      namespace: default

